version: '3'

services:
  db:
    image: mysql:5.7.37
    command: --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: invictus
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - "9906:3306"
  web:
    image: php:7.2.2-apache
    container_name: php_web
    volumes:
        - ./mlm2/:/var/www/html
    depends_on:
      - db
    ports:
      - "8100:80"
    stdin_open: true
    tty: true